import Link from "next/link";

import { studyBooks } from "@/lib/books";

export const metadata = { title: "Books" };

export default function BooksPage() {
  return <div className="mx-auto max-w-6xl"><div className="mb-8"><p className="eyebrow mb-3">Books · 本棚</p><h1 className="jp-serif text-4xl tracking-tight text-[#f5f5f2] sm:text-5xl">Keep the reference shelf close.</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-[#9297a1]">Open a book beside your Journey, or browse the full shared Drive shelf.</p></div><div className="grid gap-4 lg:grid-cols-3"><Link href="/books/drive" className="group surface-panel relative overflow-hidden p-6 transition hover:-translate-y-1 hover:border-[#e5b85c]/70"><span className="absolute right-5 top-5 jp-serif text-4xl text-[#e34a3f]/30">本</span><p className="eyebrow">Google Drive · complete shelf</p><h2 className="mt-3 pr-10 text-xl font-medium text-[#f5f5f2] group-hover:text-[#f1cf7c]">All your study books</h2><p className="mt-4 text-sm leading-6 text-[#9297a1]">Browse every book in the shared Drive folder without using Supabase Storage.</p><span className="mt-7 inline-flex text-sm font-semibold text-[#e5b85c]">Open shelf <span className="ml-2" aria-hidden="true">→</span></span></Link>{studyBooks.map((book, index) => <Link key={book.id} href={`/books/${book.id}`} className="group surface-panel relative overflow-hidden p-6 transition hover:-translate-y-1 hover:border-[#e5b85c]/70"><span className="absolute right-5 top-5 jp-serif text-4xl text-[#e34a3f]/30">{String(index + 1).padStart(2, "0")}</span><p className="eyebrow">{book.level}</p><h2 className="mt-3 pr-10 text-xl font-medium text-[#f5f5f2] group-hover:text-[#f1cf7c]">{book.title}</h2><p className="mt-1 jp-serif text-lg text-[#e5b85c]">{book.subtitle}</p><p className="mt-4 text-sm leading-6 text-[#9297a1]">{book.description}</p><span className="mt-7 inline-flex text-sm font-semibold text-[#e5b85c]">Open reader <span className="ml-2" aria-hidden="true">→</span></span></Link>)}</div><section className="surface-panel mt-7 p-6 sm:p-8"><p className="eyebrow">Study note · 使い方</p><h2 className="mt-2 text-xl font-medium text-[#f5f5f2]">Use books as references, not as a second dashboard.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#9297a1]">Kizashi owns the learning path, recall, progress, and original drills. Use a book to check a lesson, then return to the app to practice and retain it.</p></section></div>;
}
