import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { advanceWritingState, getJishoKanjiUrl, getKanjiVgUrl, getStrokeStartPoint, normalizeStrokeData, evaluateStrokeOrder } from "../lib/kanji-writing-core.js";

test("kanji writing helpers keep source URLs and stroke order deterministic", () => {
  assert.equal(getJishoKanjiUrl("駅"), "https://jisho.org/search/%E9%A7%85%20%23kanji");
  assert.equal(getKanjiVgUrl("駅"), "https://raw.githubusercontent.com/KanjiVG/kanjivg/r20260714/kanji/099c5.svg");
  assert.deepEqual(getStrokeStartPoint("M11,54.25c3.19,0.62"), { x: 11, y: 54.25 });
  assert.equal(getStrokeStartPoint("not-a-path"), null);
  assert.deepEqual(normalizeStrokeData({ character: "駅", strokes: [{ order: 1, path: "M1 1" }, { order: 2, path: "M2 2" }] }), { character: "駅", strokes: [{ order: 1, path: "M1 1" }, { order: 2, path: "M2 2" }] });
  assert.equal(normalizeStrokeData({ character: "学", strokes: [{ order: 1, path: "M1 1" }] }, "駅"), null);
  assert.equal(normalizeStrokeData({ character: "駅", strokes: [{ order: 2, path: "M1 1" }] }), null);
  assert.deepEqual(evaluateStrokeOrder(2, 1), { ok: false, message: "This should be stroke 2" });
  assert.deepEqual(evaluateStrokeOrder(2, 2), { ok: true, message: "Good" });
  assert.equal(advanceWritingState("watched", "traced"), "traced");
  assert.equal(advanceWritingState("written-from-memory", "watched"), "written-from-memory");
});

test("kanji writing surfaces keep the trainer native and references lazy", async () => {
  const trainer = await readFile(new URL("../components/learning/kanji-writing-trainer.tsx", import.meta.url), "utf8");
  const practice = await readFile(new URL("../components/practice/kanji-writing-practice.tsx", import.meta.url), "utf8").catch(() => "");
  const practicePage = await readFile(new URL("../app/(main)/practice/page.tsx", import.meta.url), "utf8");
  const localPractice = await readFile(new URL("../components/practice/local-practice.tsx", import.meta.url), "utf8");
  const accountSync = await readFile(new URL("../components/profile/account-sync.tsx", import.meta.url), "utf8");
  const dashboard = await readFile(new URL("../components/content/kanji-writing-audit.tsx", import.meta.url), "utf8");
  const mistakes = await readFile(new URL("../components/mistakes/mistake-notebook.tsx", import.meta.url), "utf8");
  const entry = await readFile(new URL("../components/library/entry-detail.tsx", import.meta.url), "utf8");
  const importer = await readFile(new URL("../scripts/import_kanjivg.py", import.meta.url), "utf8");
  const manifest = JSON.parse(await readFile(new URL("../browser/kizashi-private-frame-unlocker/manifest.json", import.meta.url), "utf8"));
  assert.match(trainer, /onPointerDown/);
  assert.match(trainer, /cancelDrawing/);
  assert.match(trainer, /onPointerCancel=\{cancelDrawing\}/);
  assert.match(trainer, /Write from memory/);
  assert.match(trainer, /ExternalSourceViewer source=\{jishoSource\}/);
  assert.match(practice, /KanjiWritingTrainer/);
  assert.match(practice, /KanjiWritingTrainer key=\{current\.id\}/);
  assert.match(practice, /initialItemId/);
  assert.match(practicePage, /kanji-writing/);
  assert.match(localPractice, /KanjiWritingPractice/);
  assert.match(accountSync, /michi-kanji-writing-updated/);
  assert.match(dashboard, /Kanji writing data/);
  assert.match(dashboard, /manifest\.version/);
  assert.match(dashboard, /manifest\.license/);
  assert.match(dashboard, /manifest\.sourceUrl/);
  assert.match(dashboard, /manifest\.attribution/);
  const contentStudio = await readFile(new URL("../components/content/content-studio.tsx", import.meta.url), "utf8");
  assert.match(dashboard, /kanjiStrokeData/);
  assert.match(dashboard, /stroke-count mismatch/);
  assert.match(dashboard, /writing practice enabled/);
  assert.match(dashboard, /normalizeStrokeData/);
  assert.match(contentStudio, /KanjiWritingAudit/);
  assert.match(entry, /KanjiWritingTrainer item=\{item\}/);
  assert.match(mistakes, /Writing repair/);
  assert.match(mistakes, /mode=kanji-writing&item=/);
  assert.match(importer, /canonical_characters/);
  assert.match(importer, /r20260714/);
  assert.match(importer, /kizashi-n5-source-review\.json/);
  assert.match(importer, /KanjiVG/);
  assert.ok(manifest.host_permissions.includes("https://jisho.org/*"));
  const strokes = JSON.parse(await readFile(new URL("../data/kanjivg-strokes.json", import.meta.url), "utf8"));
  assert.equal(strokes.version, "r20260714");
  assert.equal(strokes.sourceUrl, "https://github.com/KanjiVG/kanjivg");
  assert.equal(strokes.attribution, "KanjiVG contributors");
  assert.equal(Object.keys(strokes.characters).length, 254);
  assert.ok(Object.values(strokes.characters).every((record) => record.strokes.every((stroke, index) => stroke.order === index + 1 && stroke.path)));
});
