import { JapaneseText } from "@/components/learning/japanese-text";
import type { GrammarItem, KanjiItem, VocabularyItem } from "@/lib/types";

export function IrodoriPatternReference({ item, vocabulary = [], kanji = [] }: Readonly<{ item: GrammarItem; vocabulary?: VocabularyItem[]; kanji?: KanjiItem[] }>) {
  if (!item.sourceIds?.includes("irodori-sentence-patterns") || item.meaning?.trim()) return null;
  const lesson = item.sourceRecord?.lesson;
  const lessonTitle = item.sourceRecord?.lessonTitle;
  return <div className="rounded-xl border border-[#4b3a29] bg-[#211d18]/70 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">Irodori · source pattern</p><p className="mt-2 jp-serif text-xl text-[#e5b85c]"><JapaneseText text={item.pattern} vocabulary={vocabulary} kanji={kanji} always inspect={false} /></p></div><p className="text-right text-[10px] uppercase tracking-[.12em] text-[#9297a1]">{item.sourceLevel ?? "Irodori"}{item.sourceCourse ? ` · ${item.sourceCourse}` : ""}{lesson ? ` · ${lesson}` : ""}</p></div><p className="mt-2 text-sm leading-6 text-[#c3c7ce]">A practical sentence pattern from the Japan Foundation&apos;s Irodori materials. The original Japanese examples stay available while a Kizashi explanation is authored.</p>{lessonTitle ? <p className="mt-2 text-xs text-[#9297a1]">Lesson focus: {lessonTitle}</p> : null}<div className="mt-4 space-y-3">{item.examples.slice(0, 3).map((example) => <div key={example.japanese} className="border-l border-[#e5b85c] pl-3"><p className="jp-serif text-lg text-[#e5b85c]"><JapaneseText text={example.japanese} vocabulary={vocabulary} kanji={kanji} always /></p><p className="mt-1 text-xs text-[#9297a1]">{example.translation || "Original Irodori example · translation not added"}</p></div>)}</div><a href="https://www.irodori.jpf.go.jp/en/resources.html" target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-lg border border-[#3f4652] px-3 py-2 text-xs font-semibold text-[#c3c7ce] hover:border-[#e5b85c]">Open Irodori resources ↗</a></div>;
}
